### ISSUE TITLE
Unable to find relation <field> on <Entity> with virtual relatoin

### ISSUE THREAD

**Issue by Flusinerd** [doug-martin/nestjs-query#1001]
**Describe the bug**
Virtual Field (Relation) does not get loaded.  
I have implemented a ``RelationQueryService`` for ``MilestoneInstance`` that should allow me to get ``completedTasks`` that are a subset of the ``tasks`` attached to my ``MilestoneInstance``.

But the query fails with ``Unable to find relation completedTasks on MilestoneInstance``

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?
yes

**To Reproduce**
The DTO for milestone contains
```ts
@FilterableCursorConnection('task', () => TaskDto, { nullable: true })
```
and 
```ts
@FilterableCursorConnection('completedTasks', () => TaskDto, { nullable: true, disableRemove: true, disableUpdate: true })
```  

The ``RelationQueryService`` for ``MilestoneInstance`` looks like this:  
```ts
@Injectable()
export class MilestoneInstanceRelationQueryService extends RelationQueryService<MilestoneInstance> {
  constructor(
    queryService: MilestoneInstanceQueryService,
    usersService: UserQueryService,
    tasksService: TasksRelationQueryService
  ) {
    super(queryService, usersService, {
      completedTasks: {
        service: tasksService,
        query(dto: MilestoneInstance) {
          return {
            filter: {
              and: [
                { taskFinishedAt: { neq: null } },
                { taskMilestoneId: dto.resourceId },
              ],
            },
          };
        },
      },
    });
  }
}
```
**Expected behavior**
Be able to query for ``completedTasks`` on one and many ``MilestoneInstance``.   
Also be able to run a ``count`` aggregation on the amount of ``completedTasks``

**Screenshots**

**Desktop (please complete the following information):**
 - Node Verson [v14.15.4].
 - Nestjs-query Version [v0.23.0]

**Additional context**
Complete response:
```
{
  "errors": [
    {
      "message": "Unable to find relation completedTasks on MilestoneInstance",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "milestoneInstance",
        "completedTasks"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Unable to find relation completedTasks on MilestoneInstance",
            "    at TypeOrmQueryService.getRelationMeta (C:\\Users\\Jan\\Documents\\Datenlotse\\navigatem-production-backend\\node_modules\\@nestjs-query\\query-typeorm\\dist\\src\\services\\relation-query.service.js:212:19)",
            "    at TypeOrmQueryService.getRelationEntity (C:\\Users\\Jan\\Documents\\Datenlotse\\navigatem-production-backend\\node_modules\\@nestjs-query\\query-typeorm\\dist\\src\\services\\relation-query.service.js:217:35)",
            "    at TypeOrmQueryService.batchQueryRelations (C:\\Users\\Jan\\Documents\\Datenlotse\\navigatem-production-backend\\node_modules\\@nestjs-query\\query-typeorm\\dist\\src\\services\\relation-query.service.js:133:84)",
            "    at TypeOrmQueryService.queryRelations (C:\\Users\\Jan\\Documents\\Datenlotse\\navigatem-production-backend\\node_modules\\@nestjs-query\\query-typeorm\\dist\\src\\services\\relation-query.service.js:16:25)",
            "    at AssemblerQueryService.queryRelations (C:\\Users\\Jan\\Documents\\Datenlotse\\navigatem-production-backend\\node_modules\\@nestjs-query\\core\\dist\\src\\services\\assembler-query.service.js:51:57)",
            "    at C:\\Users\\Jan\\Documents\\Datenlotse\\navigatem-production-backend\\node_modules\\@nestjs-query\\query-graphql\\dist\\src\\loader\\query-relations.loader.js:21:51",
            "    at Array.map (<anonymous>)",
            "    at QueryRelationsLoader.loadResults (C:\\Users\\Jan\\Documents\\Datenlotse\\navigatem-production-backend\\node_modules\\@nestjs-query\\query-graphql\\dist\\src\\loader\\query-relations.loader.js:18:59)",
            "    at DataLoader._batchLoadFn (C:\\Users\\Jan\\Documents\\Datenlotse\\navigatem-production-backend\\node_modules\\@nestjs-query\\query-graphql\\dist\\src\\loader\\query-relations.loader.js:13:25)",
            "    at dispatchBatch (C:\\Users\\Jan\\Documents\\Datenlotse\\navigatem-production-backend\\node_modules\\dataloader\\index.js:275:29)"
          ]
        }
      }
    }
  ],
  "data": {
    "milestoneInstance": {
      "resourceId": "DD11433E-F36B-1410-86E6-00B3EF51C78C",
      "ownerId": "ED22433E-F36B-1410-86E5-00B3EF51C78C",
      "completedTasks": null
    }
  }
}
```

**Comment by Flusinerd** [comment]
The resolver definition looks like this:
```ts
    {
      EntityClass: MilestoneInstance,
      DTOClass: MilestoneInstanceDto,
      CreateDTOClass: CreateMilestoneInstanceDto,
      UpdateDTOClass: UpdateMilestoneInstanceDto,
      enableAggregate: true,
      ServiceClass: MilestoneInstanceRelationQueryService,
    },
```

**Comment by doug-martin** [comment]
@Flusinerd would you mind sharing your complete module definition and DTO? You can create a private repo or gist just so I can look at it, based on what you provided it _should_ work but its hard to tell what's going on without a little more to look at.

**Comment by Flusinerd** [comment]
Managed to fix it, was an issue with my QueryService functions / DTO definitions
