### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by LuisAriasC** [doug-martin/nestjs-query#1461]
I have a Mongoose Entity called DeliveryEntity which will be related on a PackageEntity

When setting a relationship with Mongoose I get the TypeError: Cannot read property 'name' of undefined.

If the relationship does not exists, the server runs well
`
import { Prop, raw, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, SchemaTypes } from 'mongoose';
import { PackageSizes, TPackageSize } from '../../../common';
import { DeliveryEntity } from '../../delivery';

export class PackageDimention {
  width: number;
  length: number;
  heigth: number;
  weigth: number;
}

export class PackageItem {
  name: string;
  description: string;
  declaredValue: number;
}

@Schema({ 
  timestamps: true,
  toJSON: { getters: true },
  toObject: { getters: true }
})
export class PackageEntity extends Document {
  
  @Prop({
    type: String,
    required: true,
  })
  trackingNumber!: string;

  @Prop({
    type: String,
    required: true,
  })
  referenceId!: string;

  @Prop({
    type: String,
    required: true,
  })
  description!: string;

  @Prop({
    type: Number,
    required: true,
    default: 0.0
  })
  declaredValue!: number;

  @Prop({ 
    type: String,
    required: true,
    enum: PackageSizes,
  })
  size!: TPackageSize;

  @Prop(raw({
    width: { type: Number },
    length: { type: Number },
    heigth: { type: Number },
    weigth: { type: Number }
  }))
  dimentions?: PackageDimention;

  @Prop(raw([{
    name: { type: String },
    description: { type: String },
    declaredValue: { type: String }
  }]))
  items!: PackageItem[];

  //@Prop({
  //  type: SchemaTypes.ObjectId,
  //  ref: 'DeliveryEntity',
  //  required: true,
  //})
  //delivery!: DeliveryEntity;

  @Prop({
    type: String,
    required: true
  })
  createdBy!: string;

  @Prop({
    type: String,
    required: true
  })
  updatedBy!: string;

  @Prop()
  createdAt!: Date;

  @Prop()
  updatedAt!: Date;
}

export const PackageEntitySchema = SchemaFactory.createForClass(
  PackageEntity,
);
`
But when I set the relationship then I get the next error:
 `
TypeError: Cannot read property 'name' of undefined
    at getQueryServiceToken (/home/luisariasc/deliveries/node_modules/@nestjs-query/core/src/decorators/helpers.ts:5:22)
    at Object.InjectQueryService (/home/luisariasc/deliveries/node_modules/@nestjs-query/core/src/decorators/inject-query-service.decorator.ts:6:30)
    at Object.<anonymous> (/home/luisariasc/deliveries/packages/deliveries-api/src/modules/package/package.resolver.ts:12:6)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/luisariasc/deliveries/packages/deliveries-api/src/modules/package/package.module.ts:17:1)
`

Here is the package entity with the relationship
`
/* Nestjs Modules */
import { Prop, raw, Schema, SchemaFactory } from '@nestjs/mongoose';
/* External Modules */
import { Document, SchemaTypes } from 'mongoose';
/* External Module Dependencies */
import { PackageSizes, TPackageSize } from '../../../common';
import { DeliveryEntity } from '../../delivery';

export class PackageDimention {
  width: number;
  length: number;
  heigth: number;
  weigth: number;
}

export class PackageItem {
  name: string;
  description: string;
  declaredValue: number;
}

@Schema({ 
  timestamps: true,
  toJSON: { getters: true },
  toObject: { getters: true }
})
export class PackageEntity extends Document {
  
  @Prop({
    type: String,
    required: true,
  })
  trackingNumber!: string;

  @Prop({
    type: String,
    required: true,
  })
  referenceId!: string;

  @Prop({
    type: String,
    required: true,
  })
  description!: string;

  @Prop({
    type: Number,
    required: true,
    default: 0.0
  })
  declaredValue!: number;

  @Prop({ 
    type: String,
    required: true,
    enum: PackageSizes,
  })
  size!: TPackageSize;

  @Prop(raw({
    width: { type: Number },
    length: { type: Number },
    heigth: { type: Number },
    weigth: { type: Number }
  }))
  dimentions?: PackageDimention;

  @Prop(raw([{
    name: { type: String },
    description: { type: String },
    declaredValue: { type: String }
  }]))
  items!: PackageItem[];

  @Prop({
    type: SchemaTypes.ObjectId,
    ref: 'DeliveryEntity',
    required: true,
  })
  delivery!: DeliveryEntity;

  @Prop({
    type: String,
    required: true
  })
  createdBy!: string;

  @Prop({
    type: String,
    required: true
  })
  updatedBy!: string;

  @Prop()
  createdAt!: Date;

  @Prop()
  updatedAt!: Date;
}

export const PackageEntitySchema = SchemaFactory.createForClass(
  PackageEntity,
);
`

And here is the DeliveryEntity
`
import { Prop, raw, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, SchemaTypes } from 'mongoose';
import { nanoid } from 'nanoid';
import {
  DeliveryCheckpointTypes, 
  TDeliveryCheckpointType,
  DeliveryCheckpointStatuses,
  TDeliveryCheckpointStatus,
  Sources,
  TSource,
  DeliveryTypes,
  TDeliveryType
} from 'src/common';
import { DeliveryStatusEntity } from '../../delivery-status/entity/delivery-status.entity';

export class DeliveryContact {
  name: string;
  email: string;
  phone: string;
  description?: string;
}

export class DeliveryLocation {
  address: string;
  zipCode: string;
  latitude: string;
  longitude: string;
  instructions?: string;
  city: string;
}

export class DeliveryPoint {
  id: string;
  contact: DeliveryContact;
  location: DeliveryLocation;
}

export class DeliveryCheckpoint {
  type: TDeliveryCheckpointType;
  status: TDeliveryCheckpointStatus;
  position: number;
  pointId: string;
  packages: string[];
}

@Schema({ 
  timestamps: true,
  toJSON: { getters: true },
  toObject: { getters: true }
})
export class DeliveryEntity extends Document {

  @Prop(raw([{
    id: { type: String, default: () => nanoid(24), required: true },
    contact: {
      name: { type: String, required: true },
      email: { type: String, required: true },
      phone: { type: String, required: true },
      description: { type: String, required: false }
    },
    location: {
      address: { type: String, required: true },
      zipCode: { type: String, required: true },
      latitude: { type: String, required: true },
      longitude: { type: String, required: true },
      instructions: { type: String, required: false },
      city: { type: String, required: true }
    }
  }]))
  pickups!: DeliveryPoint[];

  @Prop(raw([{
    id: { type: String, default: () => nanoid(24), required: true },
    contact: {
      name: { type: String, required: true },
      email: { type: String, required: true },
      phone: { type: String, required: true },
      description: { type: String, required: false }
    },
    location: {
      address: { type: String, required: true },
      zipCode: { type: String, required: true },
      latitude: { type: String, required: true },
      longitude: { type: String, required: true },
      instructions: { type: String, required: false },
      city: { type: String, required: true }
    }
  }]))
  dropoffs!: DeliveryPoint[];

  @Prop(raw([{
    type: { type: String, enum: DeliveryCheckpointTypes },
    status: { type: String, enum: DeliveryCheckpointStatuses },
    position: { type: Number },
    point: { type: String },
    packages: [{ type: String }]
  }]))
  points!: DeliveryCheckpoint[];

  @Prop({
    type: String,
    required: true,
  })
  trackingNumber!: string;

  @Prop({
    type: String,
    required: true,
    enum: Sources,
  })
  source!: TSource;

  @Prop({
    type: String,
    required: true,
  })
  referenceId!: string;

  @Prop({ 
    type: String,
    required: true,
    enum: DeliveryTypes,
  })
  type!: TDeliveryType;

  @Prop({
    type: Number,
    required: true,
    default: 0.0
  })
  price!: number;

  @Prop({
    type: String,
    required: false,
  })
  routeId?: string;

  @Prop({
    type: String,
    required: true,
  })
  customerId!: string;

  @Prop({
    type: SchemaTypes.ObjectId,
    ref: 'DeliveryStatusEntity',
    required: true,
  })
  status!: DeliveryStatusEntity;

  @Prop({
    type: String,
    required: true
  })
  createdBy!: string;

  @Prop({
    type: String,
    required: true
  })
  updatedBy!: string;

  @Prop()
  createdAt!: Date;

  @Prop()
  updatedAt!: Date;
}

export const DeliveryEntitySchema = SchemaFactory.createForClass(
  DeliveryEntity,
);

DeliveryEntitySchema.virtual('histories', {
  ref: 'DeliveryHistoryEntity',
  localField: '_id',
  foreignField: 'delivery',
});

DeliveryEntitySchema.virtual('packages', {
  ref: 'DeliveryPackageEntity',
  localField: '_id',
  foreignField: 'delivery',
});
`

I dont know what might be happening, this has never happened to me in the past before upgrading to version 0.30.0

**Desktop (please complete the following information):**
- Ubuntu: v18 .04.6
 - Node: v14.17.5
 - Nestjs-query: v0.30.0

**Comment by matt-koevort** [comment]
I'm running into the same issue as shown here:

```
TypeError: Cannot read property 'name' of undefined
    at getQueryServiceToken (/home/luisariasc/deliveries/node_modules/@nestjs-query/core/src/decorators/helpers.ts:5:22)
    at Object.InjectQueryService (/home/luisariasc/deliveries/node_modules/@nestjs-query/core/src/decorators/inject-query-service.decorator.ts:6:30)
    at Object.<anonymous> (/home/luisariasc/deliveries/packages/deliveries-api/src/modules/package/package.resolver.ts:12:6)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/luisariasc/deliveries/packages/deliveries-api/src/modules/package/package.module.ts:17:1)
```

My current suspicion is that it is caused by a cyclic dependency, so the DTO being passed to `@InjectQueryService` is undefined after being imported. Attempting to fix by not having much luck.
