### ISSUE TITLE
Class constructor TypeOrmQueryService cannot be invoked without 'new'

### ISSUE THREAD

**Issue by coder2000** [doug-martin/nestjs-query#226]
When creating a default service with nothing other than super it throws this exception:

`TypeError: Class constructor TypeOrmQueryService cannot be invoked without 'new'
    at new QueueService (/home/coder2000/Projects/speakerr/packages/server/dist/src/modules/queue/queue.service.js:37:23)
    at Injector.instantiateClass (/home/coder2000/Projects/speakerr/node_modules/@nestjs/core/injector/injector.js:289:19)
    at callback (/home/coder2000/Projects/speakerr/node_modules/@nestjs/core/injector/injector.js:76:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Injector.resolveConstructorParams (/home/coder2000/Projects/speakerr/node_modules/@nestjs/core/injector/injector.js:117:24)
    at async Injector.loadInstance (/home/coder2000/Projects/speakerr/node_modules/@nestjs/core/injector/injector.js:80:9)
    at async Injector.loadProvider (/home/coder2000/Projects/speakerr/node_modules/@nestjs/core/injector/injector.js:37:9)
    at async Promise.all (index 3)
    at async InstanceLoader.createInstancesOfProviders (/home/coder2000/Projects/speakerr/node_modules/@nestjs/core/injector/instance-loader.js:42:9)
    at async /home/coder2000/Projects/speakerr/node_modules/@nestjs/core/injector/instance-loader.js:27:13
    at async Promise.all (index 22)
    at async InstanceLoader.createInstances (/home/coder2000/Projects/speakerr/node_modules/@nestjs/core/injector/instance-loader.js:26:9)
    at async InstanceLoader.createInstancesOfDependencies (/home/coder2000/Projects/speakerr/node_modules/@nestjs/core/injector/instance-loader.js:16:9)
    at async /home/coder2000/Projects/speakerr/node_modules/@nestjs/core/nest-factory.js:81:17
    at async Function.asyncRun (/home/coder2000/Projects/speakerr/node_modules/@nestjs/core/errors/exceptions-zone.js:17:13)
    at async NestFactoryStatic.initialize (/home/coder2000/Projects/speakerr/node_modules/@nestjs/core/nest-factory.js:79:13)
    at async NestFactoryStatic.create (/home/coder2000/Projects/speakerr/node_modules/@nestjs/core/nest-factory.js:30:9)`

**Comment by doug-martin** [comment]
I tried a simple query service and it worked as expected. 

```ts
@QueryService(TodoItemEntity)
export class TodoItemService extends TypeOrmQueryService<TodoItemEntity>{
  constructor(@InjectRepository(TodoItemEntity) repository: Repository<TodoItemEntity>) {
    super(repository);
  }
}
```

Do you have simple example to help me try to reproduce the issue?

**Comment by ingolf** [comment]
The same problem.
I tried to setup "target": "es6" in my tsconfig, but it doesn't work.

**Comment by doug-martin** [comment]
Hmm, I wonder if it’s related to the typescript upgrade. @ingolf would you mind sharing your tsconfig, and ts version?

**Comment by ingolf** [comment]
@doug-martin 
ts 3.9.3


tsconfig.json:
```json
{
    "compilerOptions": {
        "lib": [
            "ES2019"
        ],
        "target": "es6",
        "module": "commonjs",
        "allowJs": true,
        "importHelpers": true,
        "esModuleInterop": true,
        "resolveJsonModule": true,
        "moduleResolution": "node",
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "forceConsistentCasingInFileNames": true,
        "strictPropertyInitialization": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
    },
    "include": [
        "./src/**/*.ts",
        "./test/**/*.ts"
    ]
}
```


tscondig.dev.json:
```json
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "rootDir": "src",
        "outDir": "build",
        "incremental": true,
        "tsBuildInfoFile": "./cache/tsconfig.build.tsbuildinfo",
        "sourceMap": true,
        "declaration": true
    },
    "include": [
        "./src/**/*.ts"
    ],
    "exclude": [
        "./src/**/*.spec.ts"
    ]
}
```

**Comment by doug-martin** [comment]
Ok I was able to reproduce, with 

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "ES5",
    "esModuleInterop": true,
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  },
  "exclude": ["node_modules", "dist"]
}
```

**Comment by doug-martin** [comment]
@ingolf thank you!

**Comment by coder2000** [comment]
Is it an issue with Typescript or something we can workaround?

**Comment by doug-martin** [comment]
@coder2000 I'm still debugging. But I'm curious did speakrr server run after this change https://github.com/coder2000/speakrr/commit/c6bbcdab626bdbbf2671ffd7f4c0831aee29b572

I see you downgraded the target version from `es2017` to `es5`, in my local testing es5 does not work, and going back through my versions I dont think it would have ever worked because the target has been `es2018`.

**Comment by doug-martin** [comment]
@ingolf in your case did `nestjs-query` work with es6 in a previous version?

**Comment by coder2000** [comment]
You're right it was my bad, I changed the target to ES2017 and it works. Sorry for the trouble.
