### ISSUE TITLE
[Question] Any way to catch errors from database and display in an elegant way

### ISSUE THREAD

**Issue by izundo-viennv** [doug-martin/nestjs-query#35]
Hi @doug-martin 
Actually, I'm a newbie with Nestjs and Graphql, so I have a question, I'm thinking about how to catch and custom errors returned by Graphql in an elegant way. Because when I try to add a unique value to database, it's failed and display a lot of info I don't want expose.

I know we can use `formatError` and exception filter to do that, but we will have many type of errors like validation error, authentication error, database error, vv and I just want to return in one format like this:
```ts
errors: [
  {
    statusCode: 400,
    message: "Bad request"
  }
]
```

I don't know best practices to follow for error handling while working with Graphql

**Comment by doug-martin** [comment]
This is an area I have really played yet with in this library. Its been on my todo list for the typeorm errors since they are they are not nice.

If you want to research and submit some ideas go for it. Im wrapping another set of changes at the moment.

**Comment by izundo-viennv** [comment]
At the moment I have no good idea for it, but I hope it released asap.

And another, how to restrict fields returned and fields can be filtered if the user doesn't have permissions. That's is my big concerns.

**Comment by doug-martin** [comment]
For now I'm going to leave this up to the developer to decide. 

The errors encountered using `nestjs-query` are not that different from what you would have to handle when doing this manually. 

If you come up with a generic way to handle this please issue a PR but for now I'm going to leave this up to the user of the library.

**Comment by Diluka** [comment]
@doug-martin what a mess, it doesn't use the `ValidationPipe`
```graphql
mutation {
  createOneUser(
    input: {
      user: {
        username: "test"
        password: "test"
        phone: "123"
        realName: "123"
      }
    }
  ) {
    id
  }
}
```

```ts
 {
      provide: APP_PIPE,
      useValue: new ValidationPipe({
        transform: true,
        validationError: {
          target: false,
          value: false,
        },
        exceptionFactory(errors: ValidationError[]) {
          return new BadRequestException([], 'ValidationErrors');
        },
      }),
    }
```

```json
{
  "errors": [
    {
      "message": "Bad Request Exception",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createOneUser"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT",
        "exception": {
          "response": {
            "statusCode": 400,
            "message": [
              {
                "target": {
                  "input": {
                    "input": {
                      "username": "test",
                      "password": "test",
                      "realName": "123",
                      "phone": "123"
                    }
                  }
                },
                "value": {
                  "input": {
                    "username": "test",
                    "password": "test",
                    "realName": "123",
                    "phone": "123"
                  }
                },
                "property": "input",
                "children": [
                  {
                    "target": {
                      "input": {
                        "username": "test",
                        "password": "test",
                        "realName": "123",
                        "phone": "123"
                      }
                    },
                    "value": {
                      "username": "test",
                      "password": "test",
                      "realName": "123",
                      "phone": "123"
                    },
                    "property": "input",
                    "children": [
                      {
                        "target": {
                          "username": "test",
                          "password": "test",
                          "realName": "123",
                          "phone": "123"
                        },
                        "value": "123",
                        "property": "phone",
                        "children": [],
                        "constraints": {
                          "isPhoneNumber": "phone must be a valid phone number"
                        }
                      }
                    ]
                  }
                ]
              }
            ],
            "error": "Bad Request"
          },
          "status": 400,
          "message": "Bad Request Exception",
          "stacktrace": [
            "Error: Bad Request Exception",
            "    at Object.exports.transformAndValidate (/mnt/d/Users/Diluka/Source/Repos/mrcs-api/node_modules/@nestjs-query/query-graphql/dist/src/resolvers/helpers.js:16:15)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
            "    at async /mnt/d/Users/Diluka/Source/Repos/mrcs-api/node_modules/@nestjs-query/query-graphql/dist/src/decorators/hook-args.decorator.js:11:22",
            "    at async /mnt/d/Users/Diluka/Source/Repos/mrcs-api/node_modules/@nestjs/core/pipes/pipes-consumer.js:15:25",
            "    at async /mnt/d/Users/Diluka/Source/Repos/mrcs-api/node_modules/@nestjs/core/pipes/pipes-consumer.js:15:25",
            "    at async /mnt/d/Users/Diluka/Source/Repos/mrcs-api/node_modules/@nestjs/core/pipes/pipes-consumer.js:15:25",
            "    at async resolveParamValue (/mnt/d/Users/Diluka/Source/Repos/mrcs-api/node_modules/@nestjs/core/helpers/external-context-creator.js:143:31)",
            "    at async Promise.all (index 1)",
            "    at async pipesFn (/mnt/d/Users/Diluka/Source/Repos/mrcs-api/node_modules/@nestjs/core/helpers/external-context-creator.js:145:13)",
            "    at async /mnt/d/Users/Diluka/Source/Repos/mrcs-api/node_modules/@nestjs/core/helpers/external-context-creator.js:68:17"
          ]
        }
      }
    }
  ],
  "data": null
}
```
