### ISSUE TITLE
super(`${description} Ensure ${Cls.name} is annotated with @nestjs/graphql @ObjectType`); when using CRUDResolver

### ISSUE THREAD

**Issue by davidevernizzi** [doug-martin/nestjs-query#622]
I'm following the docs for custom methods in resolvers (https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers#custom-methods) and I get the following error on `types.ts`:

```
./webapp/node_modules/@nestjs-query/query-graphql/dist/src/types/type.errors.js:7
        super(`${description} Ensure ${Cls.name} is annotated with @nestjs/graphql @ObjectType`);
                                           ^

TypeError: Cannot read property 'name' of undefined
    at new UnregisteredObjectType (./webapp/node_modules/@nestjs-query/query-graphql/dist/src/types/type.errors.js:7:44)
    at getGraphqlObjectMetadata (./webapp/node_modules/@nestjs-query/query-graphql/dist/src/common/external.utils.js:17:15)
    at Object.getGraphqlObjectName (./webapp/node_modules/@nestjs-query/query-graphql/dist/src/common/external.utils.js:23:12)
    at getOrCreateConnectionName (./webapp/node_modules/@nestjs-query/query-graphql/dist/src/types/connection/cursor/cursor-connection.type.js:20:30)
    at Object.CursorConnectionType (./webapp/node_modules/@nestjs-query/query-graphql/dist/src/types/connection/cursor/cursor-connection.type.js:24:28)
    at Object.ConnectionType (./webapp/node_modules/@nestjs-query/query-graphql/dist/src/types/connection/connection.type.js:19:21)
    at Object.<anonymous> (./webapp/dist/account/types.js:13:45)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)```
```

Here are my files:

`Types.ts`
```typescript
import { ConnectionType, QueryArgsType } from '@nestjs-query/query-graphql';
import { ArgsType, ObjectType } from '@nestjs/graphql';
import { AccountDTO } from './accounts.module';

export const AccountConnection = ConnectionType(AccountDTO, );

@ArgsType()
export class AccountQuery extends QueryArgsType(AccountDTO) {}
```

`accounts.resolver.ts`
```typescript
import { Filter, QueryService, InjectQueryService } from '@nestjs-query/core';
import { ConnectionType, CRUDResolver } from '@nestjs-query/query-graphql';
import { Args, Query, Resolver } from '@nestjs/graphql';
import { AccountDTO } from './accounts.module';
import { AccountEntity } from './account.entity';
import { AccountConnection, AccountQuery } from './types';

@Resolver()
export class AccountsResolver extends CRUDResolver(AccountDTO) {
  constructor(@InjectQueryService(AccountEntity) readonly service: QueryService<AccountEntity>) {
    super(service);
    console.log('in resolver');
  }

  @Query(() => AccountConnection)
  pendingAccounts(@Args() query: AccountQuery): Promise<ConnectionType<AccountDTO>> {
    // add the completed filter the user provided filter
    const filter: Filter<AccountDTO> = {
      ...query.filter,
      ...{ completed: { is: true } },
    };

    // call the original queryMany method with the new query
    return this.queryMany({ ...query, ...{ filter } });
  }
}
```

`accounts.module.ts`
```typescript
import { Module } from '@nestjs/common';
import { NestjsQueryGraphQLModule } from '@nestjs-query/query-graphql';
import { NestjsQueryTypeOrmModule } from '@nestjs-query/query-typeorm';
import { FilterableField } from '@nestjs-query/query-graphql';
import { ObjectType, Field, ID } from '@nestjs/graphql';
import { AccountEntity } from './account.entity';
import { AccountsService } from './accounts.service';
import { AccountsController } from './accounts.controller';
import { UsersModule } from '../users/users.module';
import { AccountsUsersModule } from '../accountsUsers/accountsUsers.module';
import { SettingsModule } from '../settings/settings.module';
import { AccountsResolver } from './accounts.resolver';

// TODO: move in DTO directory
@ObjectType('Account')
export class AccountDTO {
  @FilterableField(() => ID)
  id!: number;

  @FilterableField()
  json!: string;
}

@Module({
  providers: [AccountsService, AccountsResolver],
  imports: [
    NestjsQueryGraphQLModule.forFeature({
      imports: [
        NestjsQueryTypeOrmModule.forFeature([AccountEntity]),
        AccountsUsersModule,
        UsersModule,
        SettingsModule,
      ],
      services: [AccountsService],
      resolvers: [{ DTOClass: AccountDTO, ServiceClass: AccountsService, EntityClass: AccountEntity }],
    }),
  ],
  exports: [AccountsService],
  controllers: [AccountsController],
})
export class AccountsModule {}
```

Everything seems to be in line with the doc, but I get that error when I compile.

**Comment by doug-martin** [comment]
@davidevernizzi would you mind providing your account definition as well?

**Comment by davidevernizzi** [comment]
The entity you mean?

```typescript
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';
import { IsJSON } from 'class-validator';

@Entity('accounts')
export class AccountEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  owner_id: number;

  @Column('text')
  @IsJSON()
  json: string;
}
```

**Comment by davidevernizzi** [comment]
Thanks, your solutions worked. Moving to a separate file was the key. Should I update the doc to reflect this, or you change the module to prevent the issue?

**Comment by doug-martin** [comment]
Published the new docs
