### ISSUE TITLE
Use @Authorize with Extended Resolver throw an error

### ISSUE THREAD

**Issue by Nightbr** [doug-martin/nestjs-query#864]
Hello, thanks for this awesome lib :tada: 

**Describe the bug**

I'm having an issue when using the CRUDResolver class and the @Authorize decorator on the DTO.

Following this part of the doc: https://doug-martin.github.io/nestjs-query/docs/graphql/resolvers#custom-methods

It throw an error:

```shell
[Nest] 98731   - 2021-02-10 16:32:36   [ExceptionHandler] Nest could not find UserDTOAuthorizer element (this provider does not exist in the current context) +4ms
Error: Nest could not find UserDTOAuthorizer element (this provider does not exist in the current context)
```

### Have you read the [Contributing Guidelines](https://github.com/doug-martin/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes :ok_hand: 

**To Reproduce**

users.modules.ts

```TypeScript
import { Module } from '@nestjs/common';
import { UsersResolver } from './users.resolver';
import { User } from './user.entity';
import { NestjsQueryTypeOrmModule } from '@nestjs-query/query-typeorm';

@Module({
  imports: [NestjsQueryTypeOrmModule.forFeature([User])],
  providers: [UsersResolver],
})
export class AppUsersModule {}
```

users.resolver.ts
```TypeScript

import { QueryService, InjectQueryService } from '@nestjs-query/core';
import { CRUDResolver } from '@nestjs-query/query-graphql';
import { UseGuards } from '@nestjs/common';
import { Query, Resolver } from '@nestjs/graphql';
import { GqlAuthGuard } from '../../auth/guards/graphql-auth.guard';
import { CtxUser } from '../../graphql/decorator/ctx-user.decorator';
import { UserDTO } from './dto/user.dto';
import { User } from './user.entity';

@Resolver(() => UserDTO)
export class UsersResolver extends CRUDResolver(UserDTO, {
  guards: [GqlAuthGuard],
  create: { disabled: true }, // @TODO later refactor create with register
  update: { disabled: true }, // @TODO later edit User profile
  delete: { disabled: true }, // @TODO later handle User deletion 
  read: { disabled: true }, // @TODO we will use this entrypoint later to list users in team
}) {
  constructor(@InjectQueryService(User) readonly service: QueryService<User>) {
    super(service);
  }

  // Return current User
  @UseGuards(GqlAuthGuard)
  @Query(() => UserDTO, { nullable: true })
  me(@CtxUser() user: User): Promise<UserDTO | undefined> {
    return this.service.findById(user.id);
  }
}
```

dto/user.dto.ts

```TypeScript
import { FilterableField, Authorize } from '@nestjs-query/query-graphql';
import { ObjectType, GraphQLISODateTime, ID, Field } from '@nestjs/graphql';
import { getUserFromContext } from '../../../graphql/decorator/ctx-user.decorator';
import { GqlContext } from '../../../graphql/graphq-context.interface';

@ObjectType('User')
@Authorize({
  authorize: (context: GqlContext) => ({
    id: { eq: getUserFromContext(context).id },
  }),
})
export class UserDTO {
  @FilterableField(() => ID)
  id!: string;

  @Field()
  fullname: string;

  @Field()
  email: string;

  @FilterableField(() => GraphQLISODateTime)
  createdAt!: Date;

  @FilterableField(() => GraphQLISODateTime)
  updatedAt!: Date;
}

```

When compiling, it throws this error:

```TypeScript
[Nest] 99330   - 2021-02-10 16:34:07   [ExceptionHandler] Nest could not find UserDTOAuthorizer element (this provider does not exist in the current context) +5ms
Error: Nest could not find UserDTOAuthorizer element (this provider does not exist in the current context)
    at InstanceLinksHost.get (/home/myproject/node_modules/@nestjs/core/injector/instance-links-host.js:18:19)
    at Object.find (/home/myproject/node_modules/@nestjs/core/injector/module-ref.js:38:55)
    at Object.get (/home/myproject/node_modules/@nestjs/core/injector/module.js:338:28)
    at /home/myproject/node_modules/@nestjs-query/query-graphql/src/auth/default-crud.authorizer.ts:40:56
    at Map.forEach (<anonymous>)
    at new DefaultAuthorizer (/home/myproject/node_modules/@nestjs-query/query-graphql/src/auth/default-crud.authorizer.ts:36:22)
    at Injector.instantiateClass (/home/myproject/node_modules/@nestjs/core/injector/injector.js:286:19)
    at callback (/home/myproject/node_modules/@nestjs/core/injector/injector.js:42:41)
    at Injector.resolveConstructorParams (/home/myproject/node_modules/@nestjs/core/injector/injector.js:114:24)
    at Injector.loadInstance (/home/myproject/node_modules/@nestjs/core/injector/injector.js:46:9)
    at Injector.loadProvider (/home/myproject/node_modules/@nestjs/core/injector/injector.js:68:9)
    at async Promise.all (index 3)
    at InstanceLoader.createInstancesOfProviders (/home/myproject/node_modules/@nestjs/core/injector/instance-loader.js:43:9)
    at /home/myproject/node_modules/@nestjs/core/injector/instance-loader.js:28:13
    at async Promise.all (index 56)
    at InstanceLoader.createInstances (/home/myproject/node_modules/@nestjs/core/injector/instance-loader.js:27:9)

```

NOTE: if I remove the `@Authorize` part on the `UserDTO` it compiles & works (but I need to add it manually in the resolver...

```TypeScript
@Authorize({
  authorize: (context: GqlContext) => ({
    id: { eq: getUserFromContext(context).id },
  }),
})
```

**Desktop (please complete the following information):**
 - Node v12
 - Nestjs-query v0.22.0

Thanks for your help, let me know if you need anything to debug or if you can put me on a lead to fix this.

best

**Comment by luca-nardelli** [comment]
Hey, I can't diagnose your specific issue but I just bumped into this part of the documentation: https://doug-martin.github.io/nestjs-query/docs/graphql/authorization/#injectauthorizer-decorator

Maybe you have to inject it?

**Comment by Nightbr** [comment]
Yep, good point, I tried to inject it `@InjectAuthorizer(UserDTO) readonly authorizer: Authorizer<UserDTO>` but same error. Seems this service in provided by the module `NestjsQueryGraphQLModule` but the fact we use a custom resolver and don't declare it, you don't have access to the Authorizer service.

But if you import `NestjsQueryGraphQLModule`, you need to configure at least one resolver and you will override your custom resolver :/

**Comment by doug-martin** [comment]
@Nightbr I'm thinking this may be because the authorizer is set up by the NestJSQueryGraphqlModule, could you try the following and see if it works for you 

Change your resolver just expose the `me` endpoint since the query module will add the rest of the endpoints.
```ts
@Resolver(() => UserDTO)
export class UsersResolver {
  constructor(@InjectQueryService(User) readonly service: QueryService<User>) {
  }

  // Return current User
  @UseGuards(GqlAuthGuard)
  @Query(() => UserDTO, { nullable: true })
  me(@CtxUser() user: User): Promise<UserDTO | undefined> {
    return this.service.findById(user.id);
  }
}
```
add the import for the nestjs-query graphql module

```ts
import { Module } from '@nestjs/common';
import { UsersResolver } from './users.resolver';
import { User } from './user.entity';
import { NestjsQueryTypeOrmModule } from '@nestjs-query/query-typeorm';
import { NestjsQueryGraphQLModule } from '@nestjs-query/query-graphql';

@Module({
  imports: [
     NestjsQueryGraphQLModule.forFeature({
      imports: [NestjsQueryTypeOrmModule.forFeature([User])],
      resolvers: [
        {
          DTOClass: UserDTO,
          AssemblerClass: TodoItemAssembler,
          guards: [GqlAuthGuard],
          create: { disabled: true }, // @TODO later refactor create with register
          update: { disabled: true }, // @TODO later edit User profile
          delete: { disabled: true }, // @TODO later handle User deletion 
          read: { disabled: true }, // @TODO we will use this entrypoint later to list users in team
        },
      ],
    }),
  ],
  providers: [UsersResolver],
})
export class AppUsersModule {}
```

**Comment by doug-martin** [comment]
@Nightbr sorry I missed your reply. 

I'm not sure the endpoint precedence if you are overriding them entirely in your custom resolver, but if you are just adding additional queries and mutations you don't need to extend the CRUDResolver you can just use the autogenerated and have your custom resolver like the example above. 

Hope this helps :)

**Comment by Nightbr** [comment]
@doug-martin yep this is working, not extend the CRUDResolver to just expose the me (so far) :ok_hand: 

```
import { Module } from '@nestjs/common';
import { UsersController } from './users.controller';
import { UsersResolver } from './users.resolver';
import { User } from './user.entity';
import { NestjsQueryTypeOrmModule } from '@nestjs-query/query-typeorm';
import { NestjsQueryGraphQLModule } from '@nestjs-query/query-graphql';
import { UserDTO } from './dto/user.dto';
import { GqlAuthGuard } from '../../auth/guards/graphql-auth.guard';

@Module({
  imports: [
    NestjsQueryGraphQLModule.forFeature({
      imports: [NestjsQueryTypeOrmModule.forFeature([User])],
      resolvers: [
        {
          DTOClass: UserDTO,
          EntityClass: User,
          guards: [GqlAuthGuard],
          create: { disabled: true }, // @TODO later refactor create with register
          update: { disabled: true }, // @TODO later edit User profile
          delete: { disabled: true }, // @TODO later handle User deletion
          read: { disabled: true }, // @TODO we will use this entrypoint later to list users in team
        },
      ],
    }),
  ],
  providers: [UsersResolver],
  controllers: [UsersController],
})
export class AppUsersModule {}
```

Thanks :ok_hand: 

But yeah, if you are overriding the resolver, maybe you don't need the generated Authorizer. But could be great to be able to have this service as same as the QueryService.

But your solution is pretty neat and works! thank you ;)

**Comment by doug-martin** [comment]
@Nightbr plat that worked for you!

**Comment by doug-martin** [comment]
@Nightbr I addresses this in the latest version of nests-query, by adding docs for when you need to extend a CRUDResolver, as well as allowing you to set up all the appropriate providers (authorizers, hooks) etc without nests-query auto-generating a resolver.  

Check out the release notes here: https://github.com/doug-martin/nestjs-query/discussions/911

**Comment by Nightbr** [comment]
@doug-martin Awesome!! Love this new modification, I have created an issue to upgrade to v0.23 and tests this on our project! Thanks for all the work the is a master piece of software IMO!

**Comment by Nightbr** [comment]
Updated & works like a charm :heart:
